language: python
python: 
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install flake8
script:
  - flake8 --ignore=E402,E501 generate.py
  - python generate.py cv.yaml --markdown 
after_success:
  - coveralls
# group:
#   - stable
# dist: 
#   - trusty
# os: 
#   - linux